export type Lang = 'vi' | 'en'

const en = {
  appTitle: 'aaPanel Backup ER',
  dashboardSection: 'DASHBOARD',
  manage: 'MANAGE',
  home: 'Drive',
  settings: 'Settings',
  backup: 'BACKUP',
  jobs: 'Jobs',
  activity: 'Activity',
  recover: 'RECOVER',
  options: 'Options',
  available: 'Available Backups',
  files: 'FOLDERS',

  homeDashboard: 'Dashboard',
  envOverview: 'OVERVIEW',
  backupClients: 'Backup Sources',
  websiteSource: 'Website Source:',
  mysqlDatabase: 'MySQL Database:',
  cronJobs: 'Backups:',
  scheduledJobs: 'Scheduled Jobs:',
  backupTarget: 'Backup Destination',
  googleDrive: 'Google Drive:',
  localDisk: 'Local Disk:',
  syncTool: 'Sync Tool:',

  dailyBackups: 'TODAY\'S BACKUP RESULTS',
  successful: 'Successful',
  failed: 'Failed',
  nonStarted: 'Not Started',

  backupsHistory: 'TOTAL BACKUP SIZE BY DATE',
  dataGrowth: 'DAILY BACKUP SIZE VARIATION',
  noData: 'No data',

  websiteStatus: 'WEBSITE STATUS',
  domain: 'Domain',
  statusCol: 'Status',
  httpCol: 'HTTP',
  latency: 'Latency',
  loading: 'Loading...',

  lastBackup: 'LAST BACKUP SUMMARY',
  noBackupYet: 'No backup recorded yet.',
  backupSuccessful: 'Backup Successful!',
  backupFailed: 'Backup Failed!',
  job: 'Job:',
  destination: 'Destination:',
  nextSchedule: 'Next Schedule:',

  successTrend: 'BACKUP FILE COUNT HISTORY',
  success: 'Successful',
  filesCount: 'File count',
  noBackups: 'No backups',

  storageDisk: 'SERVER STORAGE',
  storageUtilization: '',
  used: 'Used',
  free: 'Free',
  serverCpu: 'CPU:',
  serverRam: 'RAM:',
  uptime: 'UPTIME:',
  na: 'N/A',

  storageDrive: 'DRIVE BACKUP FOLDER SIZE',
  apiStatus: 'API STATUS',
  online: 'ONLINE',

  backupActivity: 'Backup Activity',
  viewReport: 'View Report',
  viewDetails: 'View Details',
  jobName: 'Job Name',
  status: 'Status',
  startTime: 'Start Time',
  duration: 'Duration:',
  waiting: 'No real backup activities found. (Waiting for next cron run...)',

  jobsTitle: 'Backup Jobs',
  runNow: 'Run Now',
  schedule: 'Schedule',
  lastRun: 'Last Run',
  neverRun: 'Never Run',
  statusSuccess: 'Success',
  statusFailed: 'Failed',
  statusNever: 'Never Run',
  runningJob: 'Triggering...',
  jobTriggered: 'Job triggered. It may take a few minutes to show up on the dashboard.',
  jobFailed: 'Failed to trigger the job.',
  noJobs: 'No scheduled jobs found on the server.',

  settingsTitle: 'System Settings',
  backupConfig: 'Backup Configuration',
  scheduleInfo: 'Backup schedule (read-only, from server crontab)',
  retentionDays: 'Retention (days)',
  notifyTitle: 'Notifications',
  notifyEnabled: 'Enable Notifications',
  notifyToken: 'Telegram bot token',
  notifyChatId: 'Telegram chat ID',
  emailRecipient: 'Email recipient',
  saveConfig: 'Save Configuration',
  cancelEdit: 'Cancel',
  savedOk: 'Configuration saved successfully.',
  savedError: 'Failed to save configuration.',
  sshInfo: 'SSH Connection',
  sshHost: 'SSH Host',
  sshUser: 'SSH User',
  serverTime: 'Server Time',

  recoveryTitle: 'Recovery Options',
  recoveryMethod: 'Recovery Method',
  fullRestore: 'Full Restore (Overwrite)',
  partialRestore: 'Partial Restore (Pick folder/file)',
  downloadZip: 'Download Original Files (Zip)',
  fullRestoreHint: 'Full restore is disabled to prevent accidental overwrite. Use file download instead.',
  partialRestoreHint: 'Pick a snapshot below, then choose individual files to restore or download.',
  downloadHint: 'Download individual backup files directly from Google Drive.',
  usable: 'Available Backups',
  noSnapshots: 'No snapshots found on Google Drive.',
  date: 'Date',
  category: 'Type',
  fileName: 'File Name',
  size: 'Size',
  modified: 'Modified',
  download: 'Download',
  drvSite: 'Website Source',
  drvDatabase: 'MySQL Database',

  connectionError: 'Cannot reach the backend. Is it running?',
  lastUpdated: 'Last Updated',
  reload: 'Reload',
}

const vi: Record<LangKey, string> = {
  appTitle: 'aaPanel Backup ER',
  dashboardSection: 'DASHBOARD',
  manage: 'QUẢN LÝ',
  home: 'Drive',
  settings: 'Cài đặt',
  backup: 'SAO LƯU',
  jobs: 'Tiến trình',
  activity: 'Nhật ký',
  recover: 'KHÔI PHỤC',
  options: 'Tùy chọn',
  available: 'Bản sao lưu có sẵn',
  files: 'SỐ THƯ MỤC',

  homeDashboard: 'Dashboard',
  envOverview: 'TỔNG QUAN',
  backupClients: 'Nguồn sao lưu',
  websiteSource: 'Mã nguồn Website:',
  mysqlDatabase: 'Cơ sở dữ liệu MySQL:',
  cronJobs: 'Bản sao lưu:',
  scheduledJobs: 'Tiến trình hẹn giờ:',
  backupTarget: 'Đích Sao lưu',
  googleDrive: 'Google Drive:',
  localDisk: 'Ổ cứng cục bộ:',
  syncTool: 'Công cụ đồng bộ:',

  dailyBackups: 'CHI TIẾT BẢN SAO LƯU',
  successful: 'Thành công',
  failed: 'Thất bại',
  nonStarted: 'Chưa chạy',

  backupsHistory: 'TỔNG DUNG LƯỢNG SAO LƯU THEO NGÀY',
  dataGrowth: 'BIẾN ĐỘNG DUNG LƯỢNG GIỮA CÁC BẢN SAO LƯU THEO NGÀY',
  noData: 'Chưa có dữ liệu',

  websiteStatus: 'TRẠNG THÁI WEBSITE',
  domain: 'Tên miền',
  statusCol: 'Trạng thái',
  httpCol: 'HTTP',
  latency: 'Phản hồi',
  loading: 'Đang tải...',

  lastBackup: 'SAO LƯU GẦN NHẤT',
  noBackupYet: 'Chưa có lần sao lưu nào.',
  backupSuccessful: 'Sao lưu thành công!',
  backupFailed: 'Sao lưu thất bại!',
  job: 'Cron:',
  destination: 'Đích lưu trữ:',
  nextSchedule: 'Lịch chạy tiếp theo:',

  successTrend: 'BIỂU ĐỒ TỆP TIN SAO LƯU',
  success: 'Thành công',
  filesCount: 'Số tệp tin',
  noBackups: 'Không có sao lưu',

  storageDisk: 'DUNG LƯỢNG SERVER',
  storageUtilization: '',
  used: 'Đã dùng',
  free: 'Còn trống',
  serverCpu: 'CPU:',
  serverRam: 'RAM:',
  uptime: 'THỜI GIAN HOẠT ĐỘNG:',
  na: 'N/A',

  storageDrive: 'DUNG LƯỢNG THƯ MỤC SAO LƯU TRÊN DRIVE',
  apiStatus: 'TRẠNG THÁI API',
  online: 'TRỰC TUYẾN',

  backupActivity: 'Nhật ký sao lưu',
  viewReport: 'Xem báo cáo',
  viewDetails: 'Xem chi tiết',
  jobName: 'Tên tiến trình',
  status: 'Trạng thái',
  startTime: 'Thời gian bắt đầu',
  duration: 'Thời gian:',
  waiting: 'Chưa có hoạt động sao lưu thực tế. (Đang chờ cron chạy...)',

  jobsTitle: 'Tiến trình sao lưu',
  runNow: 'Chạy ngay',
  schedule: 'Lịch chạy',
  lastRun: 'Chạy lần cuối',
  neverRun: 'Chưa từng chạy',
  statusSuccess: 'Thành công',
  statusFailed: 'Thất bại',
  statusNever: 'Chưa chạy',
  runningJob: 'Đang kích hoạt...',
  jobTriggered: 'Đã kích hoạt tiến trình. Có thể mất vài phút để hiển thị trên dashboard.',
  jobFailed: 'Không thể kích hoạt tiến trình.',
  noJobs: 'Không tìm thấy tiến trình định kỳ trên máy chủ.',

  settingsTitle: 'Cài đặt hệ thống',
  backupConfig: 'Cấu hình Backup',
  scheduleInfo: 'Lịch sao lưu (chỉ đọc, lấy từ crontab của máy chủ)',
  retentionDays: 'Giữ bản sao trong (ngày)',
  notifyTitle: 'Thông báo',
  notifyEnabled: 'Bật thông báo',
  notifyToken: 'Telegram bot token',
  notifyChatId: 'Telegram chat ID',
  emailRecipient: 'Email nhận thông báo',
  saveConfig: 'Lưu cấu hình',
  cancelEdit: 'Hủy bỏ',
  savedOk: 'Đã lưu cấu hình thành công.',
  savedError: 'Không thể lưu cấu hình.',
  sshInfo: 'Kết nối SSH',
  sshHost: 'SSH host',
  sshUser: 'SSH user',
  serverTime: 'Giờ máy chủ',

  recoveryTitle: 'Tùy chọn khôi phục',
  recoveryMethod: 'Phương thức khôi phục',
  fullRestore: 'Khôi phục toàn bộ (Ghi đè)',
  partialRestore: 'Khôi phục từng phần (Chọn thư mục/file)',
  downloadZip: 'Tải xuống file gốc (Zip)',
  fullRestoreHint: 'Khôi phục toàn bộ bị vô hiệu để tránh ghi đè nhầm. Hãy tải file về thay thế.',
  partialRestoreHint: 'Chọn một bản sao bên dưới, sau đó chọn file để khôi phục hoặc tải về.',
  downloadHint: 'Tải từng file sao lưu trực tiếp từ Google Drive.',
  usable: 'Bản sao lưu có sẵn',
  noSnapshots: 'Chưa có bản sao lưu nào trên Google Drive.',
  date: 'Ngày',
  category: 'Loại',
  fileName: 'Tên file',
  size: 'Dung lượng',
  modified: 'Lần sửa',
  download: 'Tải xuống',
  drvSite: 'Mã nguồn website',
  drvDatabase: 'Cơ sở dữ liệu MySQL',

  connectionError: 'Không thể kết nối tới backend. Hãy kiểm tra backend đã chạy chưa.',
  lastUpdated: 'Cập nhật lúc',
  reload: 'Tải lại',
}

export type LangKey = keyof typeof en

export function tr(lang: Lang, key: LangKey): string {
  return (lang === 'vi' ? vi : en)[key]
}